In [1]:
import gym
env = gym.make('Pendulum-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

In [8]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        # env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.04871042  0.01211356 -0.02091696 -0.03550187]
[ 0.04895269  0.20752912 -0.02162699 -0.33471023]
[ 0.05310327  0.01272154 -0.0283212  -0.04892503]
[ 0.0533577  -0.18198311 -0.0292997   0.23468949]
[ 0.04971804  0.01354495 -0.02460591 -0.06708959]
[ 0.04998894  0.20901088 -0.0259477  -0.36743314]
[ 0.05416916  0.40449175 -0.03329636 -0.6681835 ]
[ 0.06225899  0.60006051 -0.04666003 -0.97116136]
[ 0.0742602   0.40559479 -0.06608326 -0.69349335]
[ 0.0823721   0.21144878 -0.07995313 -0.42232431]
[ 0.08660108  0.0175452  -0.08839962 -0.15587928]
[ 0.08695198 -0.17620716 -0.0915172   0.10765879]
[ 0.08342784 -0.3699066  -0.08936402  0.37012355]
[ 0.0760297  -0.56365277 -0.08196155  0.63334507]
[ 0.06475665 -0.75754147 -0.06929465  0.89913209]
[ 0.04960582 -0.95165933 -0.05131201  1.16925375]
[ 0.03057263 -0.75590887 -0.02792694  0.86093541]
[ 0.01545446 -0.56041796 -0.01070823  0.55960394]
[ 0.0042461  -0.36514736  0.00048385  0.26356667]
[-0.00305685 -0.56027621  0.00575518  0.55640217]


In [4]:
import gym
env = gym.make('Pendulum-v0')

In [7]:
observation = env.reset()

In [8]:
observation

array([-0.68072357,  0.73254039, -0.77474928])

In [9]:
env.action_space

Box(1,)

In [10]:
env.observation_space

Box(3,)

In [7]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [22]:
from collections import namedtuple
import numpy as np
import random

In [4]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

In [11]:
Transition

__main__.Transition

In [5]:
a = Transition(1, 2, 9, 20 )

In [6]:
a

Transition(state=1, action=2, next_state=9, reward=20)

In [8]:
a.state

1

In [44]:
memory = []

In [47]:
memory.append(Transition([8, 6], 0, 3, 2))

In [48]:
memory

[Transition(state=[1, 3], action=0, next_state=3, reward=2),
 Transition(state=[12, 4], action=0, next_state=3, reward=2),
 Transition(state=[8, 6], action=0, next_state=3, reward=2)]

In [23]:
random.sample(memory, 2)

[Transition(state=1, action=3, next_state=9, reward=39),
 Transition(state=2, action=3, next_state=49, reward=2)]

In [50]:
batch = Transition(*zip(*memory))

In [51]:
batch

Transition(state=([1, 3], [12, 4], [8, 6]), action=(0, 0, 0), next_state=(3, 3, 3), reward=(2, 2, 2))

In [59]:
state_batch = torch.tensor(batch.action).unsqueeze(1)

In [29]:
import torch

In [61]:
state_batch

tensor([[0],
        [0],
        [0]])

In [60]:
state_batch.size()

torch.Size([3, 1])