In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
a = torch.ones(3)

In [4]:
a

tensor([1., 1., 1.])

In [5]:
a[2] = 2

In [6]:
a[2]

tensor(2.)

In [7]:
type(a[2])

torch.Tensor

In [8]:
points = torch.tensor([[1,4], [2, 1], [3, 5]])
print(points)

tensor([[1, 4],
        [2, 1],
        [3, 5]])


In [9]:
points.storage()

 1
 4
 2
 1
 3
 5
[torch.LongStorage of size 6]

In [10]:
points[0, 1]

tensor(4)

In [11]:
points[0][1]

tensor(4)

In [12]:
points.dtype

torch.int64

In [13]:
params = torch.tensor([1.0, 0.0], requires_grad=True)

In [14]:
params_list = [params]
type(params_list)

list

In [15]:
x = [1, 4, 9, 24, 90]

In [16]:
x

[1, 4, 9, 24, 90]

In [23]:
torch.Tensor(x).dtype

torch.float32

In [25]:
torch.FloatTensor(x).size()

torch.Size([5])

In [28]:
torch.unsqueeze(torch.FloatTensor(x), 0).size()

torch.Size([1, 5])

In [31]:
torch.FloatTensor(x).unsqueeze(0).size()

torch.Size([1, 5])

In [33]:
action = torch.tensor([[3], [7]])

In [34]:
action

tensor([[3],
        [7]])

In [42]:
torch.max(action, 0)[1].data.numpy()[0]

1

In [3]:
a = torch.randint(1, 50, size = (2,3))

In [4]:
a

tensor([[47, 49,  3],
        [17, 35, 37]])

In [5]:
a.size()

torch.Size([2, 3])